# Generated by Django 5.2.11 on 2026-02-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_remove_comment_created_by_remove_comment_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
