# Generated by Django 5.2.11 on 2026-02-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_issue_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
